language: nodejs
sudo: required
services:
  - docker

before_install:
  - docker build -t test-react -f ./client/Dockerfile.dev ./client

script:
  - docker run test-react npm test -- --coverage


after_success:
  - docker build -t surenamas/multi-client ./client
  - docker build -t surenamas/multi-nginx ./nginx
  - docker build -t surenamas/multi-server ./server
  - docker build -t surenamas/multi-worker ./worker
#Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those Images and push them to docker hub
  - docker push surenamas/multi-client
  - docker push surenamas/multi-nginx
  - docker push surenamas/multi-server
  - docker push surenamas/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-738215445482
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

